---
apiVersion: v1
kind: Secret
metadata:
  name: sundaland-mongodb-credentials
stringData:
  SUNDALAND_MONGODB_USER: sundaland
  SUNDALAND_MONGODB_PASSWORD: sundaland
---
apiVersion: v1
kind: Secret
metadata:
  name: sundaland-pull-secret
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "bWFlbC5yb3VzdGl0Oi01QTVHNkJ6YzlzVFJudW9yVl9yR204Nk1RcDFPalY0YmdrLjAxLjB6MWt6OTJ2aQ=="
          }
      }
    }
type: kubernetes.io/dockerconfigjson
